### PR TITLE
Upgrade AWS SDK to 1.11.350

### PR DESCRIPTION
**Pull request by laurenyu**
*Description of changes:*
Upgrade AWS SDK and remove the (now useless) call for supplemental containers in one of the tests.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-spark/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have updated the [changelog](https://github.com/aws/sagemaker-spark/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate)
- [x] I have updated any necessary [documentation](https://github.com/aws/sagemaker-spark/blob/master/README.md) (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andremoeller** [comment]
Actually, https://github.com/aws/PRIVATE-sagemaker-spark-integ-tests/pull/26 was merged in. Closing!

**Comment by laurenyu** [comment]
updated the hadoop version based on @ChoiByungWook's investigation

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://fasm6a6tm9.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0432398b-f196-4a67-9717-87b74559dd3a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by laurenyu** [comment]
closing in favor of #94

**Pull request closed without merging**
